version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly" # Andere opties: "daily", "monthly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(nuget)"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5  
    commit-message:
      prefix: "deps(dotnet-sdk)"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
